- name: configure DB server
  hosts: db
  become: yes
  vars:
    login_host: db.dawss78s.online
  vars_prompt:
    name: mysql_root_password
    prompt: Please eneter the passord
    private: no
  tasks:
  - name: install DB server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable the server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: Install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMysql
      - cryptography
      executable: pip3.9
  - name: check the DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password}}"
      login_host: "{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output
  - name: print output
    ansible.builtin.debug:
      msg: "Output: {{mysql_connection_output}}"
  - name: setup the root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass{{mysql_root_password}}"
    when: mysql__connection_output.failed is true
